language: dart

dart:
  - dev

dart_task:
  - dartfmt
  - dartanalyzer: --fatal-warnings --fatal-infos .
  - test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

# Incremental pub cache and builds.
cache:
  directories:
  - $HOME/.pub-cache
