name: sync_http
version: 0.3.0-nullsafety-dev
description: Synchronous HTTP client for Dart.
homepage: https://github.com/dart-lang/sync_http

# We are not ready to publish NNBD packages yet.
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.8
