name: sync_http
version: 0.3.0-dev
description: Synchronous HTTP client for Dart.
homepage: https://github.com/dart-lang/sync_http

environment:
  sdk: '>=2.10.0 <2.11.0'

dev_dependencies:
  test: ^1.2.0

dependency_overrides:
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test
  source_maps:
    git:
      url: git://github.com/dart-lang/source_maps.git
  source_span:
    git:
      url: git://github.com/dart-lang/source_span.git
  term_glyph:
    git:
      url: git://github.com/dart-lang/term_glyph.git
  path:
    git:
      url: git://github.com/dart-lang/path.git
  charcode:
    git:
      url: git://github.com/dart-lang/charcode.git
  stream_channel:
    git:
      url: git://github.com/dart-lang/stream_channel.git
  async:
    git:
      url: git://github.com/dart-lang/async.git
  stack_trace:
    git:
      url: git://github.com/dart-lang/stack_trace.git
  pool:
    git:
      url: git://github.com/dart-lang/pool.git
  pedantic:
    git:
      url: git://github.com/dart-lang/pedantic.git
  js:
    git:
      url: git://github.com/dart-lang/sdk.git
      path: pkg/js
  boolean_selector:
    git:
      url: git://github.com/dart-lang/boolean_selector.git
  string_scanner:
    git:
      url: git://github.com/dart-lang/string_scanner.git
  matcher:
    git:
      url: git://github.com/dart-lang/matcher.git
  source_map_stack_trace:
    git:
      url: git://github.com/dart-lang/source_map_stack_trace.git
  collection:
    git:
      url: git://github.com/dart-lang/collection.git
  typed_data:
    git:
      url: git://github.com/dart-lang/typed_data.git
  meta:
    git:
      url: git://github.com/dart-lang/sdk.git
      path: pkg/meta
